//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "task")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub uuid: Uuid,
    pub token: String,
    pub cron_source: Option<String>,
    pub timestamp: Option<i64>,
    pub success: Option<bool>,
    pub error_message: Option<String>,
    #[sea_orm(column_type = "JsonBinary")]
    pub task_event_type: Json,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub task_event_result: Option<Json>,
    /// 记录创建时间（epoch 毫秒），任务**派发**时写入。
    ///
    /// 与 `timestamp` 的区别：`timestamp` 在任务完成时由结果上传回填，派发后没有回传的
    /// 行永远为 NULL，无法用于保留期判断；`created_at` 一定在派发时写入。
    /// 本列为 `m20261001_000000_add_created_at_to_task` 新增，历史行为 NULL，
    /// 由 `ng_task::retention` 按 id 安全边界回收。
    pub created_at: Option<i64>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
